{{- if .Values.global.generateSecrets }}
{{- $namespaces := list .Release.Namespace }}
{{- if and .Values.global.internalNamespace (ne .Values.global.internalNamespace .Release.Namespace) }}
{{- $namespaces = append $namespaces .Values.global.internalNamespace }}
{{- end }}
{{- $existingSecret := "" }}
{{- range $n := $namespaces }}
  {{- if not $existingSecret }}
    {{- $tmp := (lookup "v1" "Secret" $n "flightctl-kv-secret") }}
    {{- if $tmp }}{{- $existingSecret = $tmp }}{{- end }}
  {{- end }}
{{- end }}
{{- $password := "" }}
{{- if $existingSecret }}
  {{- if and (hasKey $existingSecret "data") (hasKey $existingSecret.data "password") }}
    {{- $password = (index $existingSecret.data "password") }}
  {{- else }}
    {{- fail "flightctl-kv-secret is missing data.password â€“ delete it or add the key." }}
  {{- end }}
{{- else }}
  {{- $password = (include "flightctl.generatePassword" .) }}
{{- end }}
{{- range $ns := $namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-kv-secret
  namespace: {{ $ns }}
type: Opaque
data:
  password: {{ if $.Values.kv.password }}{{ $.Values.kv.password | b64enc }}{{ else }}{{ $password }}{{ end }}
{{- end }}
{{- end }}
