{{ if eq (include "flightctl.getServiceExposeMethod" .) "route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- with .Values.global.additionalRouteLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.telemetryGateway.additionalRouteLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: flightctl-telemetry-gateway-route
  namespace: {{ .Release.Namespace }}
spec:
  host: telemetry-gateway.{{ include "flightctl.getBaseDomain" . }}
  port:
    targetPort: 4317
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  to:
    kind: Service
    name: flightctl-telemetry-gateway
    weight: 100
  wildcardPolicy: None
{{- end }}
