apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-api
  name: flightctl-api-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: flightctl-api
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: flightctl-api-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io