{{ if and $.Values.api.enabled (ne $.Values.global.exposeServicesMethod "custom") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubernetes.io/reclaimPolicy: Delete
  {{ if .Values.global.appCode }}
  labels:
    paas.redhat.com/appcode: {{ .Values.global.appCode }}
  {{ end }}
  name: flightctl-api-certs
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
{{ end }}
