apiVersion: v1
kind: Service
metadata:
  labels:
    flightctl.service: flightctl-api
    {{- include "flightctl.standardLabels" . | nindent 4 }}
  name: flightctl-api-agent
  namespace: {{ .Release.Namespace }}
spec:
  {{- if and (eq (include "flightctl.getServiceExposeMethod" .) "nodePort") .Values.global.nodePorts.agent }}
  type: NodePort
  {{- end }}
  ports:
    - name: "agent-api"
      port: 7443
      targetPort: 7443
      {{- if and (eq (include "flightctl.getServiceExposeMethod" .) "nodePort") .Values.global.nodePorts.agent }}
      nodePort: {{ .Values.global.nodePorts.agent }}
      {{- end }}
  selector:
    flightctl.service: flightctl-api
