{{ if .Values.global.auth.k8s.externalApiToken }}
kind: Secret
apiVersion: v1
metadata:
  name: flightctl-api-k8s-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-api
stringData:
  token: {{ .Values.global.auth.k8s.externalApiToken }}
type: Opaque
{{ end }}