{{ if eq (include "flightctl.getServiceExposeMethod" .) "gateway" }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: flightctl-api-route-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-api
spec:
  parentRefs:
    - name: flightctl-gateway
      sectionName: api
  hostnames:
    - agent-api.{{ include "flightctl.getBaseDomain" . }}
  rules:
    - backendRefs:
      - name: flightctl-api-agent
        port: 7443
{{ end }}
