apiVersion: v1
kind: Service
metadata:
  labels:
    flightctl.service: flightctl-api
    {{- include "flightctl.standardLabels" . | nindent 4 }}
  name: flightctl-api
  namespace: {{ .Release.Namespace }}
spec:
  {{- if and (eq (include "flightctl.getServiceExposeMethod" .) "nodePort") .Values.dev.nodePorts.api }}
  type: NodePort
  {{- end }}
  ports:
    - name: "flightctl-api"
      port: 3443
      targetPort: 3443
      {{- if and (eq (include "flightctl.getServiceExposeMethod" .) "nodePort") .Values.dev.nodePorts.api }}
      nodePort: {{ .Values.dev.nodePorts.api }}
      {{- end }}
  selector:
    flightctl.service: flightctl-api
