apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubernetes.io/reclaimPolicy: Delete
  labels:
    {{- with .Values.global.additionalPVCLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.api.additionalPVCLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-api
  name: flightctl-api-certs
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.global.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
