{{ if .Values.cliArtifacts.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-cli-artifacts
  name: flightctl-cli-artifacts
  namespace: {{ .Release.Namespace }}
spec:
  {{- if and (eq (include "flightctl.getServiceExposeMethod" .) "nodePort") .Values.dev.nodePorts.cliArtifacts }}
  type: NodePort
  {{- end }}
  ports:
    - name: "flightctl-cli-artifacts"
      port: 8090
      targetPort: 8090
      {{- if and (eq (include "flightctl.getServiceExposeMethod" .) "nodePort") .Values.dev.nodePorts.cliArtifacts }}
      nodePort: {{ .Values.dev.nodePorts.cliArtifacts }}
      {{- end }}
  selector:
    flightctl.service: flightctl-cli-artifacts
{{ end }}
