{{ if and (.Values.cliArtifacts.enabled) (eq (include "flightctl.getServiceExposeMethod" .) "gateway") }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flightctl-cli-artifacts-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-cli-artifacts
spec:
  parentRefs:
    - name: flightctl-gateway
      sectionName: cli-artifacts
  hostnames:
    - cli-artifacts.{{ include "flightctl.getBaseDomain" . }}
  rules:
    - backendRefs:
      - name: flightctl-cli-artifacts
        port: 8090
{{ end }}
