{{ if and (.Values.cliArtifacts.enabled) (eq (include "flightctl.getServiceExposeMethod" .) "route") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- with .Values.global.additionalRouteLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.cliArtifacts.additionalRouteLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-cli-artifacts
  name: flightctl-cli-artifacts-route
  namespace: {{ .Release.Namespace }}
spec:
  host: cli-artifacts.{{ include "flightctl.getBaseDomain" . }}
  port:
    targetPort: 8090
  {{- if eq (include "flightctl.getHttpScheme" .) "https" }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    {{- if .Values.global.baseDomainTlsSecretName }}
    externalCertificate:
      name: {{ .Values.global.baseDomainTlsSecretName }}
    {{- end }}
  {{- end }}
  to:
    kind: Service
    name: flightctl-cli-artifacts
    weight: 100
  wildcardPolicy: None
{{ end }}
