{{- if .Values.cliArtifacts.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    flightctl.service: flightctl-cli-artifacts
    {{- include "flightctl.standardLabels" . | nindent 4 }}
  name: flightctl-cli-artifacts
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      flightctl.service: flightctl-cli-artifacts
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        flightctl.service: flightctl-cli-artifacts
        {{- include "flightctl.standardLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecretName }}
      {{- end }}
      containers:
        - name: flightctl-cli-artifacts
          image: {{ .Values.cliArtifacts.image.image }}:{{ default .Chart.AppVersion .Values.cliArtifacts.image.tag }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.cliArtifacts.image.pullPolicy }}
          ports:
            - containerPort: 8090
              name: cli-artifacts
              protocol: TCP
          env:
            - name: CLI_ARTIFACTS_BASE_URL
              value: {{ if .Values.cliArtifacts.route.host }}{{ .Values.cliArtifacts.route.host }}{{ else }}{{ include "flightctl.getCliArtifactsUrl" . }}{{ end }}
      restartPolicy: Always
{{- end }}
