{{- if and (.Values.alertmanagerProxy.enabled) (eq (include "flightctl.getServiceExposeMethod" .) "route") -}}

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- with .Values.global.additionalRouteLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.alertmanager.additionalRouteLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: flightctl-alertmanager-proxy-route
  namespace: {{ .Release.Namespace }}
spec:
  host: alertmanager-proxy.{{ include "flightctl.getBaseDomain" . }}
  port:
    targetPort: 8443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  to:
    kind: Service
    name: flightctl-alertmanager-proxy
    weight: 100
  wildcardPolicy: None
{{- end }}
