{{- if .Values.alertmanagerProxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-alertmanager-proxy
  name: flightctl-alertmanager-proxy
  namespace: {{ .Release.Namespace }}
{{- end }}
