{{- if and .Values.alertmanagerProxy.enabled (eq (include "flightctl.getEffectiveAuthType" .) "k8s") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-alertmanager-proxy
  name: flightctl-alertmanager-proxy-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: flightctl-alertmanager-proxy
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: flightctl-alertmanager-proxy-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
