{{- if .Values.alertmanagerProxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-alertmanager-proxy-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-alertmanager-proxy
type: Opaque
stringData:
  {{- if .Values.api.caCert }}
  ca.crt: {{ .Values.api.caCert | quote }}
  {{- else }}
  ca.crt: ""
  {{- end }}
  {{- if ((.Values.global).auth).caCert }}
  ca_oidc.crt: {{ ((.Values.global).auth).caCert | quote }}
  {{- end }}
{{- end }} 