{{- if .Values.alertmanagerProxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-alertmanager-proxy-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-alertmanager-proxy
type: Opaque
stringData:
  {{- if .Values.api.caCert }}
  ca.crt: {{ .Values.api.caCert | quote }}
  {{- else }}
  ca.crt: ""
  {{- end }}
  {{- if or (and .Values.global.auth .Values.global.auth.caCert) (and .Values.auth .Values.auth.caCert) }}
  ca_oidc.crt: {{ default .Values.global.auth.caCert .Values.auth.caCert | quote }}
  {{- end }}
{{- end }} 