apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-worker
  name: flightctl-worker
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
