apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    flightctl.service: flightctl-prometheus
  name: flightctl-prometheus
  namespace:  {{ .Values.prometheus.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      flightctl.service: flightctl-prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        flightctl.service: flightctl-prometheus
    spec:
      containers:
        - name: flightctl-prometheus
          image: {{ .Values.prometheus.image }}
          ports:
            - containerPort: 9090
              name: service-api
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: flightctl-prometheus-config
              subPath: prometheus.yml
      restartPolicy: Always
      volumes:
        - name: flightctl-prometheus-config
          configMap:
            name: flightctl-prometheus-config
