apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    flightctl.service: e2e-git-server
  name: e2e-git-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      flightctl.service: e2e-git-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        flightctl.service: e2e-git-server
    spec:
      containers:
        - name: container-reg
          image: {{ .Values.gitserver.image }}
          ports:
            - containerPort: 2222
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: ssh-authorized-keys
              mountPath: /etc/ssh/authorized_keys/user
              subPath: id_rsa.pub
              readOnly: true
      volumes:
        - name: ssh-authorized-keys
          secret:
            secretName: e2e-git-ssh-keys
            defaultMode: 0644
      restartPolicy: Always
