apiVersion: v1
kind: Service
metadata:
  labels:
    flightctl.service: e2e-git-server
  name: e2e-git-server
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - name: "registry"
      port: 3222
      targetPort: 2222
      {{ if .Values.global.nodePorts.gitserver }}
      nodePort: {{ .Values.global.nodePorts.gitserver }}
      {{ end }}
  selector:
    flightctl.service: e2e-git-server
