apiVersion: v1
kind: Secret
metadata:
  name: e2e-git-ssh-keys
  namespace: {{ .Release.Namespace }}
data:
  id_rsa.pub: {{ .Files.Get "secrets/git-ssh.pub" | b64enc }}
  id_rsa: {{ .Files.Get "secrets/git-ssh.key" | b64enc }}
