apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    flightctl.service: e2e-git-server
  name: e2e-git-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      flightctl.service: e2e-git-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        flightctl.service: e2e-git-server
    spec:
      containers:
        - name: container-reg
          image: {{ .Values.gitserver.image }}
          ports:
            - containerPort: 22
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: ssh-keys
              mountPath: /tmp/ssh-keys
              readOnly: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              cp /tmp/ssh-keys/id_rsa.pub /home/user/.ssh/authorized_keys
              chown user:user /home/user/.ssh/authorized_keys
              chmod 600 /home/user/.ssh/authorized_keys
              while true; do /usr/sbin/sshd -D -e; sleep 1; done
          #TODO(make sure the container works with this security context in openshift)
          #securityContext:
          #  allowPrivilegeEscalation: true
          #  capabilities:
          #    add:
          #    - NET_BIND_SERVICE
          #    - SYS_CHROOT
      volumes:
        - name: ssh-keys
          secret:
            secretName: e2e-gitserver-keys
      restartPolicy: Always
