database:
    hostname: flightctl-db
    type: pgsql
    port: 5432
    name: flightctl
    user: admin
    password: adminpass   # we should funnel this via secrets instead
service: {}
queue:
    amqpUrl: amqp://user:password@flightctl-mq:5672/
