{{ if and .Values.pamIssuer.enabled .Values.global.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    flightctl.service: flightctl-pam-issuer
    {{- include "flightctl.standardLabels" . | nindent 4 }}
  name: flightctl-pam-issuer
  namespace: {{ .Release.Namespace }}
{{ end }}

