{{- if and .Values.imageBuilderApi .Values.imageBuilderApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-imagebuilder-api
  name: flightctl-imagebuilder-api
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 8445
      protocol: TCP
      targetPort: 8445
  selector:
    flightctl.service: flightctl-imagebuilder-api
{{- end }}