{{- if and .Values.imageBuilderApi .Values.imageBuilderApi.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-imagebuilder-api
  name: flightctl-imagebuilder-api
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
{{- end }}