{{- if and .Values.imageBuilderApi .Values.imageBuilderApi.enabled (eq (include "flightctl.getEffectiveAuthType" .) "k8s") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-imagebuilder-api
  name: flightctl-imagebuilder-api-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: flightctl-imagebuilder-api
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: flightctl-imagebuilder-api-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
