apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flightctl-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flightctl-prometheus
subjects:
  - kind: ServiceAccount
    name: default
    namespace: flightctl-external
