{{ if .Values.kv.enabled }}
---
# Secret to store the Redis password
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-kv-secret
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.kv.password | b64enc }}
---
# ConfigMap for Redis configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: flightctl-kv-config
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
data:
  redis.conf: |-
    bind 0.0.0.0
    protected-mode yes
    port 6379
    dir /var/lib/redis/data

    # Logging
    loglevel {{ default "warning" .Values.kv.loglevel }}

    # Snapshotting configuration
    save {{ .Values.kv.save }}
    dbfilename dump.rdb

    # AOF configuration
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
---
# StatefulSet for Redis
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flightctl-kv
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    flightctl.service: flightctl-kv
spec:
  serviceName: flightctl-kv
  replicas: 1
  selector:
    matchLabels:
      flightctl.service: flightctl-kv
  template:
    metadata:
      labels:
        flightctl.service: flightctl-kv
    spec:
      securityContext:
        fsGroup: 1001
      {{- if .Values.global.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecretName }}
      {{- end }}
      containers:
        - name: flightctl-kv
          image: {{ .Values.kv.image.image }}:{{ .Values.kv.image.tag }}
          imagePullPolicy: {{ .Values.kv.image.pullPolicy }}
          ports:
            - name: kv
              containerPort: 6379
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flightctl-kv-secret
                  key: REDIS_PASSWORD
          command:
            - "redis-server"
            - "/etc/redis/redis.conf"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          volumeMounts:
            - name: flightctl-kv-data
              mountPath: /var/lib/redis/data
            - name: flightctl-kv-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
      volumes:
        - name: flightctl-kv-config
          configMap:
            name: flightctl-kv-config
            defaultMode: 0644
  volumeClaimTemplates:
    - metadata:
        name: flightctl-kv-data
        annotations:
          kubernetes.io/reclaimPolicy: Delete
        {{- if .Values.global.appCode }}
        labels:
          paas.redhat.com/appcode: {{ .Values.global.appCode }}
        {{- end }}
      spec:
        storageClassName: {{ .Values.global.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
{{ end }}
