{{- if and (eq (include "flightctl.getEffectiveAuthType" .) "k8s") .Values.global.auth.k8s.createAdminUser }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flightctl-admin
  namespace: {{ default .Release.Namespace .Values.global.auth.k8s.rbacNs }}
  labels:
    app: flightctl
    component: default-user

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flightctl-admin-binding
  namespace: {{ default .Release.Namespace .Values.global.auth.k8s.rbacNs }}
  labels:
    app: flightctl
    component: default-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flightctl-admin
subjects:
  - kind: ServiceAccount
    name: flightctl-admin
    namespace: {{ default .Release.Namespace .Values.global.auth.k8s.rbacNs }}

{{- end }}
