{{- if eq (include "flightctl.enableMulticlusterExtensions" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flightctl-device-registration
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
rules:
  - verbs:
      - get
    apiGroups:
      - flightctl.io
    resources:
      - devices
  - verbs:
      - create
    apiGroups:
      - flightctl.io
    resources:
      - repositories

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: managedcluster-import-controller-flightctl
  namespace: multicluster-engine
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flightctl-device-registration
subjects:
  - kind: ServiceAccount
    name: managedcluster-import-controller-v2
    namespace: multicluster-engine
{{- end }}
