{{- if eq (include "flightctl.enableMulticlusterExtensions" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flightctl-device-registration
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
rules:
  - verbs:
      - get
    apiGroups:
      - flightctl.io
    resources:
      - devices
  - verbs:
      - get
      - create
      - update
    apiGroups:
      - flightctl.io
    resources:
      - repositories

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: managedcluster-import-controller-flightctl
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flightctl-device-registration
subjects:
  - kind: ServiceAccount
    name: managedcluster-import-controller-v2
    namespace: {{ .Values.global.multiclusterEngineNamespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flightctl-device-registration-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - flightctl-ca-bundle

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: managedcluster-import-controller-flightctl-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flightctl-device-registration-ca
subjects:
  - kind: ServiceAccount
    name: managedcluster-import-controller-v2
    namespace: {{ .Values.global.multiclusterEngineNamespace }}
{{- end }}
