{{ if and (eq (.Values.global).target "standalone") (eq (.Values.global.auth).type "builtin") }}
{{- if eq .Values.global.exposeServicesMethod "gateway" }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: flightctl-gateway
      sectionName: keycloak
  hostnames:
    - auth.{{ include "flightctl.getBaseDomain" . }}
  rules:
    - backendRefs:
      - name: keycloak
        port: 8080
{{- end }}
{{ end }}