{{- if eq .Values.db.type "builtin" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: flightctl-db
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-db
data:
  enable-superuser.sh: |
    #!/bin/bash

    _psql () { psql --set ON_ERROR_STOP=1 "$@" ; }

    # Ensure POSTGRESQL_MASTER_USER is treated as a superuser
    if [ -n "${POSTGRESQL_MASTER_USER}" ]; then
      echo "Granting superuser privileges to ${POSTGRESQL_MASTER_USER}"
      _psql -c "ALTER ROLE ${POSTGRESQL_MASTER_USER} WITH SUPERUSER;"
    fi
{{- end }}
