{{- if eq .Values.db.type "builtin" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    flightctl.service: flightctl-db
    {{- include "flightctl.standardLabels" . | nindent 4 }}
  name: flightctl-db
  namespace:  {{ default .Release.Namespace .Values.global.internalNamespace }}
spec:
  {{- if and (eq (include "flightctl.getServiceExposeMethod" .) "nodePort") .Values.global.nodePorts.db }}
  type: NodePort
  {{- end }}
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      {{- if and (eq (include "flightctl.getServiceExposeMethod" .) "nodePort") .Values.global.nodePorts.db }}
      nodePort: {{ .Values.global.nodePorts.db }}
      {{- end }}
  selector:
    flightctl.service: flightctl-db
{{- end }}