{{ if and .Values.ui.enabled (or ((.Values.global).auth).caCert .Values.ui.auth.caCert) }}
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-ui-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-ui
type: Opaque
stringData:
  ca_auth.crt: {{ default ((.Values.global).auth).caCert .Values.ui.auth.caCert | quote }}
{{ end }}
