{{ if .Values.ui.enabled }}
{{ $caCrt := default (include "flightctl.getAuthCaCrt" .) .Values.ui.auth.caCert }}
{{ if $caCrt }}
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-ui-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-ui
type: Opaque
stringData:
  ca_auth.crt: {{ $caCrt | quote }}
{{ end }}
{{ end }}
