{{ if .Values.ui.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: flightctl-ui
  namespace: {{ .Release.Namespace }}
  labels:
    flightctl.service: flightctl-ui
    {{- include "flightctl.standardLabels" . | nindent 4 }}
  {{- if eq (include "flightctl.enableMulticlusterExtensions" .) "true" }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: flightctl-ui-serving-cert
  {{- end }}
spec:
  {{- if eq (include "flightctl.getServiceExposeMethod" .) "nodePort" }}
  type: NodePort
  {{- end }}
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
      {{- if eq (include "flightctl.getServiceExposeMethod" .) "nodePort"}}
      nodePort: {{ .Values.dev.nodePorts.ui }}
      {{- end }}
  selector:
    flightctl.service: flightctl-ui
{{ end }}
