{{ if .Values.ui.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-ui-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-ui
type: Opaque
stringData:
  ca.crt: {{ .Values.api.caCert | quote }}
  {{- if or ((.Values.global).auth).caCert .Values.ui.auth.caCert }}
  ca_oidc.crt: {{ default ((.Values.global).auth).caCert .Values.ui.auth.caCert | quote }}
  {{- end }}
{{ end }}
