{{ if and (not (eq .Values.global.target "acm")) (eq (include "flightctl.getServiceExposeMethod" .) "route") }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: flightctl-ui
  namespace: {{ .Release.Namespace }}
  {{- if (.Values.global).appCode }}
  labels:
    external-exposed: 'true'
    paas.redhat.com/appcode: {{ .Values.global.appCode }}
    shard: external
  {{ end }}
spec:
  {{- if .Values.baseURL }}
  host:  {{ .Values.baseURL }}
  {{- else }}
  host:  ui.{{ include "flightctl.getBaseDomain" . }}
  {{- end }}
  to:
    kind: Service
    name: flightctl-ui
    weight: 100
  port:
    targetPort: 8080-tcp
  {{- if eq (include "flightctl.getUIHttpScheme" .) "https" }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    {{- if (.Values.global.baseDomainTls).cert }}
    certificate: {{ .Values.global.baseDomainTls.cert | quote }}
    key: {{ .Values.global.baseDomainTls.key | quote }}
    {{- end }}
  {{- end }}
  wildcardPolicy: None
{{ end }}
    