global:
  nodePorts:
    registry: ""
    gitserver: ""
    prometheus: ""
    jaegerUi: ""
  imagePullPolicy: IfNotPresent
  imagePullSecretName: ""
  internalNamespace: ""
registry:
  image:
    repository: quay.io/flightctl/e2eregistry
    tag: "2"
  route: true
  hostName: ""
gitserver:
  image:
    repository: quay.io/flightctl-tests/git-server
    tag: "latest"
prometheus:
  image:
    repository: quay.io/prometheus/prometheus
    tag: "v2.54.1"
jaeger:
  enabled: false
  image:
    repository: jaegertracing/all-in-one
    tag: "1.35"
    pullPolicy: ""
  storageType: memory
  maxTraces: 50000
  otlpEnabled: true
  logLevel: info
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"
