global:
  nodePorts:
    registry: ""
    gitserver: ""
    prometheus: ""
registry:
  image: docker.io/library/registry:2
  route: true
  hostName: ""
gitserver:
  image: localhost/git-server:latest
prometheus:
  image: quay.io/prometheus/prometheus:v2.54.1
